### ISSUE TITLE
Cannot ssh into device pwd required

### ISSUE THREAD

**Issue by GPrimola** [lawik/fleet#1]
Hi,

I'm trying to `ssh` into the device but it asks a password.
I've also tried with user `root` or `nerves` but happens the same.

<img width="363" alt="Screenshot 2024-08-07 at 21 09 30" src="https://github.com/user-attachments/assets/cd0b3260-513d-4280-977b-79c2de1cd5b8">

**Comment by lawik** [comment]
Right, I haven't set up keys that I can share currently. Might do that in a revision. If it responds to ping and has internet access it should be joining the fleet and should be working but there isn't an easy way to verify currently.
